name: kita_hack_app
description: "recordItemProject."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.8
  # Stable ML Kit packages for offline custom model support
  google_mlkit_image_labeling: ^0.14.2
  google_mlkit_text_recognition: ^0.15.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ml/food_model.tflite
